import { Inter, Montserrat } from "next/font/google";
import { Toaster } from 'sonner';
import "./globals.css";
import 'react-perfect-scrollbar/dist/css/styles.css';
import { ThemeProvider } from "@/ui-components/theme";
import { MenuProvider } from "@/ui-components/sidebar";
const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({
   weight: ["400", "500", "600", "700"],
   display: "swap",
   variable: "--font-montserrat",
   subsets: ["latin"]
})
export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body className={`${montserrat.className} ${montserrat.variable}`}>
            <ThemeProvider>{children}</ThemeProvider>
            <Toaster />
         </body>
      </html>
   );
}
