import { Inter, Montserrat } from "next/font/google";
import { Toaster } from 'sonner';
import "./globals.css";
import 'react-perfect-scrollbar/dist/css/styles.css';
import { ThemeProvider } from "@/ui-components/sidebar";
import AuthProvider from "@/authentication/auth";
const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({
   weight: ["400", "500", "600", "700"],
   display: "swap",
   variable: "--font-montserrat",
   subsets: ["latin"]
})
export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang="en">
         <body className={`${montserrat.className} ${montserrat.variable}`}>
            <AuthProvider>
               <ThemeProvider>
                  {children}
                  <Toaster richColors />
               </ThemeProvider>
            </AuthProvider>
         </body>
      </html>
   );
}
